package com.cognizant.lineage.upload.constants;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class TechnologyConstants {
	
	public static final String BTEQ = "bteq";
    public static final String MLOAD = "mload";
	public static final String TPT = "tpt";
	public static final String SHELL_1 = "shell";
	public static final String POWERBI = "powerbi";
	public static final String VIEW = "view";
	public static final String PROCEDURE = "procedure";
	public static final String QLIKVIEW = "qlikview";
	public static final String FUNCTION = "function";
	public static final String MACRO = "macro";
	public static final String PACKAGE = "package";
	public static final String TRIGGER = "trigger";
	public static final String INFORMATICA = "Informatica";
	public static final String ORACLE = "Oracle";
	public static final String ODI = "ODI";
	public static final String COGNOS = "Cognos";
	public static final String IDMC = "IDMC";
	public static final String SCHEDULAR = "Schedular";
	public static final String TIVOLI = "Tivoli";
	public static final String SSIS = "SSIS";
	public static final String TABLEAU = "Tableau";
	public static final String DATASTAGE_SCENARIO1 = "datastage_scenario1";
	public static final String DATASTAGE_SCENARIO2 = "datastage_scenario2";
	public static final String DATASTAGE_SCENARIO3 = "datastage_scenario3";
	public static final String SCRIPTS = "Scripts";
	public static final String PYTHON_SCRIPT = "python";

	public static final String SHELL_2 = "Shell";
	public static final String ORACLE_PROCEDURE = "ORACLE-PROCEDURE";
	public static final String ORACLE_FUNCTION = "ORACLE-FUNCTION";
	public static final String ORACLE_PACKAGE = "ORACLE-PACKAGE";
	public static final String ORACLE_TRIGGER = "ORACLE-TRIGGER";
	public static final String ORACLE_VIEW = "ORACLE-VIEW";
	public static final String ORACLE_ODI = "ORACLE-ODI";
	public static final String TERADATA = "Teradata";
	public static final String TERADATA_TPT = "TERADATA-TPT";
	public static final String TERADATA_VIEW = "TERADATA-VIEW";
	public static final String TERADATA_BTEQ = "TERADATA-BTEQ";
	public static final String TERADATA_PROCEDURE = "TERADATA-PROCEDURE";
	public static final String TERADATA_FUNCTION = "TERADATA-FUNCTION";
	public static final String TERADATA_MACRO = "TERADATA-MACRO";
	public static final String TERADATA_MLOAD = "TERADATA-MLOAD";
	public static final String BI = "BI";
	public static final String BI_TABLEAU = "BI-TABLEAU";
	public static final String POWER_BI = "POWER-BI";
	public static final String BI_QLIKVIEW = "BI-QLIKVIEW";
	public static final String BI_COGNOS = "BI-COGNOS";
	public static final String INFORMATICA_CAPS = "INFORMATICA";
	public static final String INFORMATICA_DEFAULT = "INFORMATICA_DEFAULT";
	public static final String INFORMATICA_DYNAMIC = "INFORMATICA_DYNAMIC";
	public static final String DATASTAGE = "datastage";

	public static final String MS_SQL_SERVER = "MS SQL Server";
	public static final String MS_SQL_SERVER_VIEW = "MS SQL SERVER-VIEW";
	public static final String MS_SQL_SERVER_PROCEDURE = "MS SQL SERVER-PROCEDURE";
	public static final String MS_SQL_SERVER_FUNCTION = "MS SQL SERVER-FUNCTION";
	public static final String MS_SQL_SERVER_TRIGGER = "MS SQL SERVER-TRIGGER";
	public static final String ACTION_STORED_PROCEDURE = "StoredProcedure";
	public static final String SNAPLOGIC = "Snaplogic";
	public static final String SSRS = "SSRS";
	public static final String SSRS_SCRIPT_PARSING = "SSRS SCRIPT PARSING";

	public static final List<String> ALLOWED_ACTIONS = new ArrayList<>(Arrays.asList(BTEQ,
			TPT, SHELL_1, POWERBI, VIEW, PROCEDURE, QLIKVIEW, MLOAD, PYTHON_SCRIPT));
	
	public static final Map<String, String> TECH_PARAMS = new HashMap<>(Map.ofEntries(
	        Map.entry(BTEQ, TERADATA),
	        Map.entry(TPT, TERADATA),
	        Map.entry(VIEW, TERADATA),
	        Map.entry(PROCEDURE, TERADATA),
            Map.entry(MLOAD, TERADATA),
            Map.entry(SHELL_1, SHELL_2),
            Map.entry(PYTHON_SCRIPT, SCRIPTS),
	        Map.entry(POWERBI, BI),
	        Map.entry(QLIKVIEW, BI)));

	public static final String CLEANSING = "CLEANSING";
	public static final String SCRIPT_LINEAGE_CLEANSING = "SCRIPT LINEAGE CLEANSING";
	public static final String SQL_PARSING = "SQL PARSING";
	public static final String BEFORE_PARSING = "BEFORE PARSING";
	public static final String PARSING = "PARSING";
	public static final String UNNEST = "UNNEST";
	public static final String ALIAS_HANDLING = "ALIAS HANDLING";
	public static final String VOLATILE_HANDLING = "VOLATILE HANDLING";
	public static final String LINEAGE_IDENTIFICATION = "LINEAGE IDENTIFICATION AND DATA MERGING";
	//public static final String COLUMN_LEVEL_LINEAGE_IDENTIFICATION = "COLUMNLEVELLINEAGE IDENTIFICATION";
	public static final String IDMC_FILE_PARSING = "IDMC File Parsing";
	public static final String TIVOLI_FILE_PARSING = "Tivoli File Parsing";
	public static final String SSIS_SCRIPT_PARSING = "SSIS Script Parsing";
	public static final String MLOAD_FILES_CLEANSING = "mload_files_cleansing";
	public static final String PYTHON_SCRIPTS_PARSING = "python_scripts_parsing";
	public static final String SCRIPT_LINEAGE_IDENTIFICATION = "SCRIPT LINEAGE IDENTIFICATION AND DATA MERGING";
	public static final String SCRIPT_PREPROCESSING = "SCRIPT PRE-PROCESSING"; //(Preprocessing step + cleansing steps)
	public static final String SCRIPT_PARSING = "SCRIPT PARSING"; //(all steps after cleansing till volatile handling)
	
	public static final String[] DATASTAGE_DYNAMIC_STEPS1 = {SCRIPT_LINEAGE_CLEANSING, "DataStageXmlParsing",
			"SourceTargetIdentification", LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] DATASTAGE_DYNAMIC_STEPS2 = {SCRIPT_LINEAGE_CLEANSING, "DataStageXmlParsing",
			"SourceTargetIdentification", "Data stage queries processing", SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST,
			ALIAS_HANDLING, VOLATILE_HANDLING, LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] DATASTAGE_DYNAMIC_STEPS3 = {SCRIPT_LINEAGE_CLEANSING, "DataStageXmlParsing",
			"SourceTargetIdentification", "Data stage queries processing", SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST,
			ALIAS_HANDLING, VOLATILE_HANDLING, LINEAGE_IDENTIFICATION, LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] BTEQ_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING,
			VOLATILE_HANDLING, LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION}; //COLUMN_LEVEL_LINEAGE_IDENTIFICATION

	public static final String[] VIEW_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};
	
	public static final String[] TERADATA_VIEW_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION}; //COLUMN_LEVEL_LINEAGE_IDENTIFICATION

	public static final String[] PROCEDURE_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] TERADATA_PROCEDURE_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION}; //COLUMN_LEVEL_LINEAGE_IDENTIFICATION

	public static final String[] TPT_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING,
			VOLATILE_HANDLING, LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] QLIKVIEW_STEPS = {SCRIPT_LINEAGE_CLEANSING, "Extracting queries from logs", SQL_PARSING,
			BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] POWERBI_STEPS = {"Powerbi_queries", CLEANSING, CLEANSING, //SCRIPT_LINEAGE_CLEANSING
			CLEANSING, CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING,
			VOLATILE_HANDLING, LINEAGE_IDENTIFICATION}; //SCRIPT_LINEAGE_IDENTIFICATION
	
	public static final String[] PYTHON_STEPS = {PYTHON_SCRIPTS_PARSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING,
			VOLATILE_HANDLING, LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] COGNOS_STEPS = {SCRIPT_LINEAGE_CLEANSING, "Cognos XML Parsing",
	LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] IDMC_STEPS = {SCRIPT_LINEAGE_CLEANSING, "IDMC File Parsing",
	LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};
	
	public static final String[] TIVOLI_STEPS = {"Tivoli File Parsing", LINEAGE_IDENTIFICATION};
	
	public static final String[] SSIS_STEPS = {"SSIS Script Parsing", SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING,
			VOLATILE_HANDLING, LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

    public static final String[] MLOAD_STEPS = {SCRIPT_LINEAGE_CLEANSING, "mload_files_cleansing",
            LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] INFORMATICA_DEFAULT_STEPS = {SCRIPT_LINEAGE_CLEANSING, "XML Parsing",
	LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] INFORMATICA_DYNAMIC_STEPS = {SCRIPT_LINEAGE_CLEANSING, "XML Parsing", "Informatica file creation",
			CLEANSING, CLEANSING, CLEANSING, CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING,
			PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING, LINEAGE_IDENTIFICATION, LINEAGE_IDENTIFICATION,
			SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] TABLEAU_STEPS = {SCRIPT_LINEAGE_CLEANSING, "Tableau XML Parsing",
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] SHELL_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, LINEAGE_IDENTIFICATION,
			SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] ORACLE_ODI_STEPS = {SCRIPT_LINEAGE_CLEANSING, "ODI XML Parsing", "ODI Table Cleansing",
			SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING, LINEAGE_IDENTIFICATION,
			SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] ORACLE_TRIGGER_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] ORACLE_PACKAGE_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] ORACLE_FUNCTION_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] ORACLE_VIEW_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] ORACLE_PROCEDURE_STEPS = {SCRIPT_LINEAGE_CLEANSING, CLEANSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING, VOLATILE_HANDLING,
			LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] SNAPLOGIC_STEPS = {SCRIPT_LINEAGE_CLEANSING, SCRIPT_PARSING, LINEAGE_IDENTIFICATION,
			SCRIPT_LINEAGE_IDENTIFICATION};

	public static final String[] SSRS_STEPS = {SCRIPT_LINEAGE_CLEANSING, SSRS_SCRIPT_PARSING, CLEANSING, CLEANSING,
			CLEANSING, CLEANSING, CLEANSING, SQL_PARSING, BEFORE_PARSING, PARSING, UNNEST, ALIAS_HANDLING,
			VOLATILE_HANDLING, LINEAGE_IDENTIFICATION, SCRIPT_LINEAGE_IDENTIFICATION};

	public static final Map<String, String[]> STEPS_FOR_TECH = new LinkedHashMap<>(Map.ofEntries(
			Map.entry(SHELL_2, SHELL_STEPS),
			Map.entry(COGNOS, COGNOS_STEPS),
			Map.entry(POWERBI, POWERBI_STEPS),
			Map.entry(QLIKVIEW, QLIKVIEW_STEPS),
			Map.entry(IDMC, IDMC_STEPS),
			Map.entry(TIVOLI, TIVOLI_STEPS),
			Map.entry(SSIS, SSIS_STEPS),
			Map.entry(TABLEAU, TABLEAU_STEPS),
			Map.entry(SNAPLOGIC, SNAPLOGIC_STEPS),
			Map.entry(SSRS, SSRS_STEPS),
			Map.entry(PYTHON_SCRIPT, PYTHON_STEPS),

			Map.entry(TERADATA_VIEW, TERADATA_VIEW_STEPS),
			Map.entry(TERADATA_BTEQ, BTEQ_STEPS),
			Map.entry(TERADATA_PROCEDURE, TERADATA_PROCEDURE_STEPS),	
			Map.entry(TERADATA_TPT, TPT_STEPS),
			Map.entry(TERADATA_MLOAD, MLOAD_STEPS),

			Map.entry(MS_SQL_SERVER_VIEW, VIEW_STEPS),
			Map.entry(MS_SQL_SERVER_FUNCTION, VIEW_STEPS),
			Map.entry(MS_SQL_SERVER_TRIGGER, VIEW_STEPS),
			Map.entry(MS_SQL_SERVER_PROCEDURE, PROCEDURE_STEPS),

			Map.entry(INFORMATICA_DEFAULT, INFORMATICA_DEFAULT_STEPS),
			Map.entry(INFORMATICA_DYNAMIC, INFORMATICA_DYNAMIC_STEPS),

			Map.entry(DATASTAGE_SCENARIO1, DATASTAGE_DYNAMIC_STEPS1),
	        Map.entry(DATASTAGE_SCENARIO2, DATASTAGE_DYNAMIC_STEPS2),
	        Map.entry(DATASTAGE_SCENARIO3, DATASTAGE_DYNAMIC_STEPS3),

			Map.entry(ORACLE_ODI, ORACLE_ODI_STEPS),
			Map.entry(ORACLE_PROCEDURE, ORACLE_PROCEDURE_STEPS),
			Map.entry(ORACLE_VIEW, ORACLE_VIEW_STEPS),
			Map.entry(ORACLE_PACKAGE, ORACLE_PACKAGE_STEPS),
			Map.entry(ORACLE_TRIGGER, ORACLE_TRIGGER_STEPS),
			Map.entry(ORACLE_FUNCTION, ORACLE_FUNCTION_STEPS)
			));

	public static final Map<String, Integer> NO_OF_STEPS_FOR_TECH = new LinkedHashMap<>(Map.ofEntries(
			Map.entry(SHELL_2, SHELL_STEPS.length),
			Map.entry(COGNOS, COGNOS_STEPS.length),
			Map.entry(POWERBI, POWERBI_STEPS.length),
			Map.entry(QLIKVIEW, QLIKVIEW_STEPS.length),
			Map.entry(IDMC, IDMC_STEPS.length),
			Map.entry(TIVOLI, TIVOLI_STEPS.length),
			Map.entry(SSIS, SSIS_STEPS.length),
			Map.entry(TABLEAU, TABLEAU_STEPS.length),
			Map.entry(SNAPLOGIC, SNAPLOGIC_STEPS.length),
			Map.entry(SSRS, SSRS_STEPS.length),
			Map.entry(PYTHON_SCRIPT, PYTHON_STEPS.length),

			Map.entry(MS_SQL_SERVER_VIEW, VIEW_STEPS.length),
			Map.entry(MS_SQL_SERVER_FUNCTION, VIEW_STEPS.length),
			Map.entry(MS_SQL_SERVER_TRIGGER, VIEW_STEPS.length),
			Map.entry(MS_SQL_SERVER_PROCEDURE, PROCEDURE_STEPS.length),

			Map.entry(INFORMATICA_DEFAULT, INFORMATICA_DEFAULT_STEPS.length),
			Map.entry(INFORMATICA_DYNAMIC, INFORMATICA_DYNAMIC_STEPS.length),
	        Map.entry(DATASTAGE_SCENARIO1, DATASTAGE_DYNAMIC_STEPS1.length),
	        Map.entry(DATASTAGE_SCENARIO2, DATASTAGE_DYNAMIC_STEPS2.length),
	        Map.entry(DATASTAGE_SCENARIO3, DATASTAGE_DYNAMIC_STEPS3.length),

			Map.entry(ORACLE_ODI, ORACLE_ODI_STEPS.length),
			Map.entry(ORACLE_PROCEDURE, ORACLE_PROCEDURE_STEPS.length),
			Map.entry(ORACLE_VIEW, ORACLE_VIEW_STEPS.length),
			Map.entry(ORACLE_PACKAGE, ORACLE_PACKAGE_STEPS.length),
			Map.entry(ORACLE_TRIGGER, ORACLE_TRIGGER_STEPS.length),
			Map.entry(ORACLE_FUNCTION, ORACLE_FUNCTION_STEPS.length),

			Map.entry(TERADATA_VIEW, TERADATA_VIEW_STEPS.length),
			Map.entry(TERADATA_BTEQ, BTEQ_STEPS.length),
			Map.entry(TERADATA_PROCEDURE, TERADATA_PROCEDURE_STEPS.length),	
			Map.entry(TERADATA_TPT, TPT_STEPS.length),
			Map.entry(TERADATA_MLOAD, MLOAD_STEPS.length)
			));

	// Insert the step names in uppercase for smooth processing
	public static final Map<String, String> STEPS_REDUCTION_MAP = new LinkedHashMap<>(Map.ofEntries(
			Map.entry(CLEANSING, SCRIPT_PREPROCESSING),
			Map.entry(SCRIPT_LINEAGE_CLEANSING, SCRIPT_PREPROCESSING),
			Map.entry("DATASTAGEXMLPARSING", SCRIPT_PREPROCESSING),
			Map.entry("SOURCETARGETIDENTIFICATION", SCRIPT_PREPROCESSING),
			Map.entry("DATA STAGE QUERIES PROCESSING", SCRIPT_PREPROCESSING),
			Map.entry("EXTRACTING QUERIES FROM LOGS", SCRIPT_PREPROCESSING),
			Map.entry("POWERBI_QUERIES", SCRIPT_PREPROCESSING),
			Map.entry("COGNOS XML PARSING", SCRIPT_PREPROCESSING),
			Map.entry("TABLEAU XML PARSING", SCRIPT_PREPROCESSING),
			Map.entry("IDMC FILE PARSING", SCRIPT_PREPROCESSING),
			Map.entry("TIVOLI FILE PARSING", SCRIPT_PREPROCESSING),
			Map.entry("SSIS SCRIPT PARSING", SCRIPT_PREPROCESSING),
			Map.entry("XML PARSING", SCRIPT_PREPROCESSING),
			Map.entry("INFORMATICA FILE CREATION", SCRIPT_PREPROCESSING),
			Map.entry("ODI XML PARSING", SCRIPT_PREPROCESSING),
			Map.entry("ODI TABLE CLEANSING", SCRIPT_PREPROCESSING),
			Map.entry("MLOAD_FILES_CLEANSING", SCRIPT_PREPROCESSING),
			Map.entry("PYTHON_SCRIPTS_PARSING", SCRIPT_PREPROCESSING),
			Map.entry(SSRS_SCRIPT_PARSING, SCRIPT_PREPROCESSING),
			Map.entry(SCRIPT_PARSING, SCRIPT_PARSING),
			Map.entry(SQL_PARSING, SCRIPT_PARSING),
			Map.entry(BEFORE_PARSING, SCRIPT_PARSING),
			Map.entry(PARSING, SCRIPT_PARSING),
			Map.entry(UNNEST, SCRIPT_PARSING),
			Map.entry(ALIAS_HANDLING, SCRIPT_PARSING),
			Map.entry(VOLATILE_HANDLING, SCRIPT_PARSING),
			Map.entry(LINEAGE_IDENTIFICATION, LINEAGE_IDENTIFICATION),
			Map.entry(SCRIPT_LINEAGE_IDENTIFICATION, LINEAGE_IDENTIFICATION)
//			Map.entry(COLUMN_LEVEL_LINEAGE_IDENTIFICATION, COLUMN_LEVEL_LINEAGE_IDENTIFICATION)
			));
}
