spring.application.name=JPA-Relationship

spring.datasource.url=jdbc:postgresql://localhost:5433/testdb
spring.datasource.username=postgres
spring.datasource.password=Nb@2259653
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true