package com.cognizant.lineage.security;

public final class QueryConstantSecurity {

	private QueryConstantSecurity() {
		throw new IllegalAccessError("Utility class");
	}
	
	public static final String USER_DTL = "SELECT USER_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATUS_CODE,LICENSE_VALIDATOR,"
			+ " CREATION_DATE,CREATED_BY,LAST_UPDATE_BY,LAST_UPDATE_DATE,PASSWORD_EXPIRY_DATE,"
			+ " (SELECT MAX(ACCESS_DATE) FROM APPLICATION_USERS_AUDIT_LOG WHERE USER_ID=APPLICATION_USERS.USER_ID) ACCESS_DATE,"
			+ " (SELECT STRING_AGG(AUTHORITY, ',') FROM APPLICATION_AUTHORITIES WHERE USER_ID=APPLICATION_USERS.USER_ID) AUTHORITIES"
			+ " FROM APPLICATION_USERS WHERE USER_ID=?"
			+ " AND STATUS_CODE='ACTIVE' AND (PASSWORD_EXPIRY_DATE IS NULL OR PASSWORD_EXPIRY_DATE >=?)";
	public static final String ALL_USER_DTL = "SELECT USER_ID,CASE WHEN PASSWORD IS NOT NULL THEN NULL END AS PASSWORD,"
			+ " FIRST_NAME,LAST_NAME,EMAIL,STATUS_CODE,LICENSE_VALIDATOR,"
			+ " CREATION_DATE,CREATED_BY,LAST_UPDATE_BY,LAST_UPDATE_DATE,PASSWORD_EXPIRY_DATE,"
			+ " (SELECT MAX(ACCESS_DATE) FROM APPLICATION_USERS_AUDIT_LOG WHERE USER_ID=APPLICATION_USERS.USER_ID) ACCESS_DATE,"
			+ " (SELECT STRING_AGG(AUTHORITY, ',') FROM APPLICATION_AUTHORITIES WHERE USER_ID=APPLICATION_USERS.USER_ID) AUTHORITIES"
			+ " FROM APPLICATION_USERS ORDER BY USER_ID";
	public static final String AUTHORITY_DTL = "SELECT USER_ID,AUTHORITY FROM APPLICATION_AUTHORITIES WHERE USER_ID=?";
	public static final String USER_DTL_INSERT= "INSERT INTO APPLICATION_USERS( USER_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATUS_CODE,"
			+ "LICENSE_VALIDATOR,"
			+ "CREATION_DATE,CREATED_BY,LAST_UPDATE_BY,LAST_UPDATE_DATE,PASSWORD_EXPIRY_DATE ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ";
	public static final String AUTHORITY_DTL_INSERT = "INSERT INTO APPLICATION_AUTHORITIES ( USER_ID,AUTHORITY )"
			+ " VALUES(?,?)";
	public static final String USER_UPDATE_STATUS_INACTIVE= "UPDATE APPLICATION_USERS SET STATUS_CODE=?,"
			+ "LAST_UPDATE_BY=?,LAST_UPDATE_DATE=? WHERE USER_ID=?";
	public static final String USER_UPDATE_STATUS_ACTIVE= "UPDATE APPLICATION_USERS SET STATUS_CODE=?,"
			+ "LAST_UPDATE_BY=?,LAST_UPDATE_DATE=? WHERE USER_ID=?";
	public static final String USER_DTL_BY_USER_ID_AND_PASSWORD = "SELECT USER_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATUS_CODE,LICENSE_VALIDATOR,"
			+ " CREATION_DATE,CREATED_BY,LAST_UPDATE_BY,LAST_UPDATE_DATE,PASSWORD_EXPIRY_DATE,"
			+ " (SELECT MAX(ACCESS_DATE) FROM APPLICATION_USERS_AUDIT_LOG WHERE USER_ID=APPLICATION_USERS.USER_ID) ACCESS_DATE,"
			+ " (SELECT STRING_AGG(AUTHORITY, ',') FROM APPLICATION_AUTHORITIES WHERE USER_ID=APPLICATION_USERS.USER_ID) AUTHORITIES"
			+ " FROM APPLICATION_USERS WHERE USER_ID=?"
			+ " AND PASSWORD=? AND STATUS_CODE='ACTIVE'";
	public static final String USER_UPDATE_PASSWORD= "UPDATE APPLICATION_USERS SET PASSWORD=?,PASSWORD_EXPIRY_DATE=?,"
			+ "LAST_UPDATE_BY=?,LAST_UPDATE_DATE=? WHERE USER_ID=?";
	public static final String USER_DTL_BY_USER_ID_AND_STATUS_CODE = "SELECT USER_ID,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL,STATUS_CODE,LICENSE_VALIDATOR,"
			+ " CREATION_DATE,CREATED_BY,LAST_UPDATE_BY,LAST_UPDATE_DATE,PASSWORD_EXPIRY_DATE,"
			+ " (SELECT MAX(ACCESS_DATE) FROM APPLICATION_USERS_AUDIT_LOG WHERE USER_ID=APPLICATION_USERS.USER_ID) ACCESS_DATE,"
			+ " (SELECT STRING_AGG(AUTHORITY, ',') FROM APPLICATION_AUTHORITIES WHERE USER_ID=APPLICATION_USERS.USER_ID) AUTHORITIES"
			+ " FROM APPLICATION_USERS WHERE USER_ID=?"
			+ " AND STATUS_CODE=?";
	public static final String INSERT_USERS_AUDIT_LOG="INSERT INTO APPLICATION_USERS_AUDIT_LOG(USER_ID,USER_AUTHORITIES,ACCESS_URI,ACCESS_DATE) VALUES (?,?,?,?)";
	public static final String ALL_READ_ONLY_USER="SELECT DISTINCT APPLICATION_USERS.USER_ID USER_ID,APPLICATION_USERS.FIRST_NAME FIRST_NAME,"
			+ "APPLICATION_USERS.LAST_NAME LAST_NAME FROM APPLICATION_USERS,APPLICATION_AUTHORITIES "
			+ "WHERE APPLICATION_USERS.USER_ID=APPLICATION_AUTHORITIES.USER_ID "
			+ "AND STATUS_CODE='ACTIVE' AND APPLICATION_AUTHORITIES.AUTHORITY='READ-ONLY-USER'";
	public static final String ALL_AUTHORITIES="SELECT AUTHORITIE_NAME FROM AUTHORITIES_MASTER WHERE IS_ACTIVE=TRUE";
	
}