server.port=8761
spring.application.name=EurekaDiscoveryService

logging.file.name=C:/Nitesh/LogLocation/${spring.application.name}.log
logging.level.root=info

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

#prevent the application from registering itself as a client with Eureka server
#prevent the client from fetching registery information from Eureka server
#Eureka server will start immediately without waiting to get information from other Eureka servers
