#server.port=7777
#spring.application.name=ApiGateway

#eureka.client.service-url.default-zone=http://localhost:8761/eureka
#eureka.client.instance.preferIpAddress=true

#spring.main.web-application-type=reactive