server.port=7001
spring.application.name=lineage-service
spring.cache.type=none

## Application log
logging.file.name=${logFileLocation}/${spring.application.name}.log
#logging.file.name=C:/IDMCLog/a.log
logging.level.root=info
## End Application log
	
#DbMetadatCapture
OracleScriptLocation=${base.path.location}/python/module_lineage/oracle_object_type.py
TeradataScriptLocation=${base.path.location}/python/module_lineage/teradata_object_type.py
SqlServerScriptLocation=${base.path.location}/python/module_lineage/sql_server_object_type.py

#BusinessLineage
BusinessLineageScriptLocation=${base.path.location}/python/xyz.py
BusinessLineageExcelScriptLocation=${base.path.location}/python/business_lineage_report.py
BusinessLineageExcelPath=/opt/apache-tomcat-9.0.44/webapps/BusinessLineageExcel

#ModuleLineage
moduleLineageScriptLocation=${base.path.location}/bash_scripts/script_files/module_lineage.py

#DbObjectsExtraction
dbobjects.extraction.path=${base.path.location}/extract_directory

#DuplicateQueryAnalysis
duplicateQueryAnalysisFileLocation=${base.path.location}/sourceFiles/duplicateQueryAnalysisUploadedFiles
duplicateQueryAnalysisScriptLocation=${base.path.location}/bash_scripts/script_files/duplicate_query_info.py

#TableLineageReportGeneration
pythonScriptLocation=${base.path.location}/python/stream_paths_to_csv.py

## Required for global properties file
## datasource details 
#spring.datasource.url=jdbc:postgresql://10.0.224.14:5432/assessment?currentSchema=semantic
spring.datasource.url=jdbc:postgresql://13.213.188.19:5432/new_assessment?currentSchema=semantic
spring.datasource.username=assessment
spring.datasource.password=assessment-123
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true

vault.ip=13.213.188.19
vault.url=http://13.213.188.19:7113/service/vault/secrets
vault.dbconnectiondetails.path=lineage/server_connection
vault.path=lineage/assessment-db-local

#
### Required for global properties file
## Log folder location
#logFileLocation=C:/Log
##logFileLocation=/home/assessment/logs
#
### Required for global properties file
## Max total files upload size is 1GB.
#spring.servlet.multipart.max-file-size=1024MB
#spring.servlet.multipart.max-request-size=1024MB
#
### Required for global properties file
## informatica service properties
#informaticaInputFiles=C:/Users/2112791/Downloads/testing_directory/uploads_test
##informaticaInputFiles=/home/assessment/informatica/InformaticaXML
#infaFileScript=informatica_file_creation.py
#
### Required for global properties file
## bteq service properties
#bteqScriptLocation=/apps/opt/application/assessment/lineage_part/python_test
#bteqInputFiles=C:/Users/2112791/Downloads/testing_directory/uploads_test
##bteqInputFiles=/home/assessment/teradataBteq/bteqInputLocation
#bteqOutputFileLocation=/home/assessment/teradataBteq/bteqOutputLocation
##bteqLogFileDirectory=/home/assessment/teradataBteq/consoleLogFromApplication
#bteqScriptName=lineage_shell_script.sh
#bteqPythonScriptLocation=/home/assessment/lineage_part/python_test
#bteqPythonScriptName=gremlin-data-load.py
#
#commonScriptLocation=/home/assessment/lineage_part/python_test
#commonScriptName=gremlin-data-load.py
#
##below script to be place in common script location
#sourceToTargetPythonScriptName=simple.py
#
#
##tpt and power bi related variables
##path is same as bash script
#tptStepZeroScripName=tpt_cleansing_script.py
#powerbiStepZeroScriptName=power_bi_cleansing_script.py
#ouputDirForTptAndPowerbi=/home/assessment/teradataBteq/tptbiOutput
#
#qlikViewScript=lineage_shell_script_log_to_sql.sh
#
##for ksh
kshScriptName=ksh_cleansing_script.py
#
#
##csrf token for all phython scripts
csrfToken=assessment
#
##odi details
#ODIXMLFileLocation=C:/Users/2112791/Downloads/testing_directory/uploads_test
##ODIXMLFileLocation=/home/assessment/Oracle/ODI
#ODIPythonScriptName=lineage_shell_script_odi.sh
#ODIPythonScriptLocation=/apps/opt/application/assessment/lineage_part/python_test

#SchemaDetails
lineage.schema=semantic
lineage.presentation.schema=presentation

base.path.location=/home/assessment/multi_sess_lineage/


#Script-->displaylineage-->pyvisLibrary
pyvisLibraryScriptNameNodeOrScript=vis_graph.py
pyvisLibraryScriptLocationNodeOrScript=${base.path.location}/python
pyvisLibraryScriptNameTech=vis_graph_filtered.py
pyvisLibraryScriptLocationTech=${base.path.location}/python
pyvisDisplayTableLineageScript=${base.path.location}/python/gen_lineage_json.py
knowledgeGraphScript=${base.path.location}/python/knowledge_graph/gen_kgraph_json.py

#Script-->uploadpage-->odi
ODIXMLFileLocation=${base.path.location}/sourceFiles/ODI
ODIPythonScriptName=lineage_shell_script_odi.sh
ODIPythonScriptLocation=${base.path.location}/bash_scripts/script_files

#Script-->uploadpage-->informatica
infaFileScript=informatica_file_creation.py
informaticaInputFiles=${base.path.location}/sourceFiles/InformaticaXML
informaticaParameterFileLocation=${base.path.location}/sourceFiles/InformaticaParameterFile

#Script-->uploadpage-->mload
mloadScriptName=mload_files_lineage.py
mloadScriptLocation=${base.path.location}/python

#Script-->uploadpage-->bteq
bteqScriptName=lineage_shell_script.sh
bteqScriptLocation=${base.path.location}/bash_scripts/script_files
bteqPythonScriptName=graph-data-load.py
bteqPythonScriptLocation=${base.path.location}/python
bteqInputFiles=${base.path.location}/sourceFiles/bteqInputLocation
bteqOutputFileLocation=${base.path.location}/sourceFiles/bteqOutputLocation
bteqLogFileDirectory=${base.path.location}/sourceFiles/consoleLogFromApplication

#Script-->uploadpage-->MsSqlServer
sqlServerFileInputLocation=${base.path.location}/sourceFiles/msSqlServerInputLocation
sqlServerFileOutputLocation=${base.path.location}/sourceFiles/msSqlServerOutputsLocation

#Script-->uploadpage-->qlikview (Path same as bteq script)
qlikViewScript=lineage_shell_script_log_to_sql.sh

#Script-->uploadpage-->tpt/powerbi (Path same as bteq script)
tptStepZeroScripName=tpt_cleansing_script.py
powerbiStepZeroScriptName=power_bi_cleansing_script.py
ouputDirForTptAndPowerbi=${base.path.location}/sourceFiles/tptbiOutput

#Script-->databasepage-->oracle/teradata
ExtractDbObjectForTeradataScriptName=teradata_obj_loading.py
ExtractDbObjectForTeradataScriptLocation=${base.path.location}/bash_scripts/teradata_code
ExtractDbObjectForOracleScriptName=oracle_obj_load.py
ExtractDbObjectForOracleScriptLocation=${base.path.location}/bash_scripts/oracle_code
ExtractDbObjectForMSSQLScriptName=sqlserver_extract.py
ExtractDbObjectForMSSQLServerScriptLocation=${base.path.location}/python/sqlserver_extraction

#Script-->scriptconfigurationpage-->odi
importScriptName=import_scripts.py
importScriptLocation=${base.path.location}/bash_scripts/script_files

#InputFileLocation-->uploadpage-->cognos/tableau
cognosInputFiles=${base.path.location}/sourceFiles/cognosInputLocation
#tableauInputFiles=${base.path.location}/sourceFiles/tableauInputLocation
tableauInputFiles=C:/Nitesh/SourceFiles/UploadedFiles

#Excel-->displaylineage-->completedata/subgraphdata/pyvisexcel
excelFileNameAll=completeData.xlsx
excelFileNameSub=subGraphData.xlsx
excelFileLocation=${tomcat.path.location}/webapps/GraphExcel
excelGenerationScriptLocation=${base.path.location}/python/islandwise_fullpaths_to_csv.py
technicalLineageReportFileLocation=${tomcat.path.location}/webapps/excel_report/

#LogDetails
logFileLocation=${base.path.location}/logs/
#logging.file.name=${logFileLocation}/${spring.application.name}.log   
#logging.level.root=info 
#LOG_LEVEL=INFO

#Miscellaneous
commonScriptName=graph-data-load.py
commonScriptLocation=${base.path.location}/python
sourceToTargetPythonScriptName=possiblepaths-json.py

pysparkFileUploadLocation = C:/NiteshCodes/FileInput

#SprintPlanning
moduleLoaderScriptLocation=${base.path.location}/python/module_loader.py
extractionPythonFile=${base.path.location}/python/volumetric_analysis/vol_extraction.py
sprintWorksheetsStorageLocation=/home/assessment/work/sprint_planning_worksheets
sprintWorksheetPythonFile=${base.path.location}/python/sprint_worksheets.py
wavePlanReportFileLocation=${tomcat.path.location}/webapps/excel_report/
##########################################################

#configuring application name

datastageFileUploadLocation=${base.path.location}/sourceFiles/datastageUploadedFiles
dataStageScriptLocation=${base.path.location}/bash_scripts/script_files
dataStageScriptName=lineage_shell_script_datastage.sh


#writeMethodNames=write_to_db_table_insert-4 , write_to_db-4, write-csv:dbtable:saveAsTable, write_to_db_table_truncate_and_load-4, write_database-3
#readMethodNames=read-tableName:csv:parquet, read_db_table-5, read_db_query-, read_database-
#writeMethodNames=read_csv-1
#readMethodNames=read_csv-1

data_df_parquet = spark.read.parquet("/home/documents/customer.csv",header=True,inferSchema=True)
skipKeyWordsPattern=^(if|else|elif|while|try|except|logger|log|logging|import|from|for)
writeMethodNames=write_to_db_table_insert-4~table , write_to_db-4~table, write-csv~file:dbtable~table:saveAsTable~table, write_to_db_table_truncate_and_load-4~table, write_database-3~table
readMethodNames=read-tableName~table:csv~file:parquet~file, read_db_table-5~table, read_db_query-~table, read_database-~table

foldersToSkip=config,properties,resources,test
configPropertyFolder=config
captureDataFlowTypes=TABLE

run.option=python
folderOrFileName=/files/test

specialClassTokens=cursor-execute~1$table$source:fetch~1$table$source:fetchOne~1$table$source


#column level lineage
columnLevelLineageFilePath = C:/Users/874373/Videos/Log/
columnLineageNodeGenerationScriptLocation=${base.path.location}/python/
columnLineageNodeGenerationScriptName=column_lineage_json.py

#TomcatPathLocation
tomcat.path.location=/opt/apache-tomcat-9.0.44

#classification usable
classificationPythonScript=classification/main.py
executionLogLocation=${logFileLocation}/ExecutionLog

#for security
jwtSecretKey=asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
jwtTokenExpireDurationInMilliSec=36000000

## Password validaty in days
initialPasswordValidityInDays=7
passwordValidityInDays=365

## Auto password generation and send via email
## If Yes then password will be auto generated
## and send via email to user. If No, then use
## manual password (manualPassword) and share to user.

autoPasswordGenarationAndEmailSend=Yes
manualPassword=Datascan@1234
domainName=cognizant.com

#CSLGlobalExcel
globalExcelFilePathForLineage=${tomcat.path.location}/webapps/csl-global-excel/

#Snaplogic Constants
snaplogicUploadLocation=${base.path.location}/sourceFiles/snaplogicInputLocation

#SprintPlan
SprintPlanScriptForObjectBased=${base.path.location}/python/wave_calculation.py
SprintPlanScriptForApplicationBased=${base.path.location}/python/wave_calculation_scripts.py
ScriptForShiftNodesObjectBased=${base.path.location}/python/shift_nodes_wave_calc.py
ScriptForShiftNodesApplicationBased=${base.path.location}/python/shift_nodes_wave_calc_scripts.py
NodeBasedSprintPlanScriptForObjectBased=${base.path.location}/python/node_based_wave_calc.py
NodeBasedSprintPlanScriptForApplicationBased=${base.path.location}/python/node_based_wave_calc_scripts.py

#IDMC
IDMCFileUploadLocation=C:/Nitesh/SourceFiles/UploadedFiles

#TivoliJobs
TivoliFileUploadLocation=C:/Nitesh/SourceFiles/UploadedFiles

#SSIS
SSISRawScriptLocation=C:/Users/874373/Music/SSIS/SSISRawScripts
SSISParsedScriptLocation=C:/Users/874373/Music/SSIS/SSISParsedScripts
SSISCleansedScriptLocation=C:/Users/874373/Music/SSIS/SSISCleansedScripts

#SSRS
ssrsUploadLocation=${base.path.location}/sourceFiles/SSRS/uploadedFiles/
ssrsInputLocation=${base.path.location}/sourceFiles/SSRS/parsedFiles/
ssrsOutputLocation=${base.path.location}/sourceFiles/SSRS/cleansedFiles/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#script lineage
scriptLineageCleansingScript=${base.path.location}/python/script_lineage/script_lineage.py
scriptLineageScriptOutputLocation=${base.path.location}/sourceFiles/script_lineage_output/
scriptLineageLoadingScript=${base.path.location}/python/graph-data-load-scripts.py

#PythonScriptUpload
pythonScriptForUploadFunctionality=${base.path.location}/bash_scripts/script_files/python_file_query_extractor.py
outputLocationForLineageShellScript=${base.path.location}/sourceFiles/PythonScriptOutput