'''
*@date    Sep 4, 2023
* This m_smoketest_infa_complex_utils.py file is a submodule of m_smoketest_infa_complex.py file.
* This code is generated by Cognizant� Data and Intelligence Toolkit (CDIT).
'''
import pyspark
from pyspark.sql.dataframe import DataFrame
from pyspark.sql import Window,WindowSpec,Column
from pyspark.sql.functions import *
from datetime import datetime
from pyspark.sql.session import SparkSession
from pyspark.sql.types import *
import json
from cdit.cditutils import CditUtil
import logging


class MSmoketestInfaComplex:

    _spark = None
    _logger = None
    _mapping_vars = {}
    _prg_config = {}
    _wf_config = {}

    def __init__(self, spark, logger, mapping_vars, prg_config, wf_config):

        self._spark = spark
        self._logger = logger
        self._prg_config = prg_config
        self._wf_config = wf_config
        self._mapping_vars = mapping_vars

    def df_lkp_demo_source1_query(self):
        self._logger.log_info('Passing query as a parameter for df_lkp_demo_source1 ')

        query =""" SELECT LKP_DEMO_SOURCE1.CUST_ID, LKP_DEMO_SOURCE1.ACCT_ID, LKP_DEMO_SOURCE1.FIRST_NM, LKP_DEMO_SOURCE1.LAST_NM, LKP_DEMO_SOURCE1.CUST_ADDR, LKP_DEMO_SOURCE1.CUST_PHN, LKP_DEMO_SOURCE1.CUST_EML_ADDR, LKP_DEMO_SOURCE1.AGE, LKP_DEMO_SOURCE1.DOB, LKP_DEMO_SOURCE1.CUST_TYP FROM LKP_DEMO_SOURCE1 ORDER BY ACCT_ID """

        return query

    def df_lkp_demo_source2_query(self):
        self._logger.log_info('Passing query as a parameter for df_lkp_demo_source2 ')

        query =""" SELECT LKP_DEMO_SOURCE2.CUST_ID, LKP_DEMO_SOURCE2.CRDT_SCORE, LKP_DEMO_SOURCE2.MAX_CRDT_SCORE, LKP_DEMO_SOURCE2.MIN_CRDT_SCORE, LKP_DEMO_SOURCE2.MAX_CRDT_LMT, LKP_DEMO_SOURCE2.CURR_CRDT_BAL_AMT, LKP_DEMO_SOURCE2.AVG_INC_AMT FROM LKP_DEMO_SOURCE2 ORDER BY CUST_ID """

        return query


    def get_df_exptrans1(self, df_demo_source4:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans1')
        #Expression Transformation  #Original Exp : LTRIM(ACCT_DESC)
        df_exptransltrim1 = df_demo_source4.withColumn("o_ACCT_DESC", ltrim(col("ACCT_DESC")))

        #Expression Transformation  #Original Exp : INITCAP(ACCT_STAT_CD)
        df_exptransinitcap2 = df_exptransltrim1.withColumn("o_ACCT_STAT_CD", initcap(col("ACCT_STAT_CD")))

        return df_exptransinitcap2


    def get_df_exptrans21(self, df_lkp_demo_source3:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans21')
        #Expression Transformation  #Original Exp : INITCAP(TX_TYPE_DESC)
        df_exptrans2initcap1 = df_lkp_demo_source3.withColumn("o_TX_TYPE_DESC", initcap(col("TX_TYPE_DESC")))

        return df_exptrans2initcap1


    def get_df_exptrans31(self, df_rtrtrans1:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans31')
        #Expression Transformation  #Original Exp : Upper(LAST_NM3)
        df_exptrans3upper1 = df_rtrtrans1.withColumn("o_LAST_NM", upper(col("LAST_NM")))

        #Expression Transformation  #Original Exp : Upper(FIRST_NM3)
        df_exptrans3upper2 = df_exptrans3upper1.withColumn("o_FIRST_NM", upper(col("FIRST_NM")))

        return df_exptrans3upper2


    def get_df_exptrans41(self, df_rtrtrans2:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans41')
        #Expression Transformation  #Original Exp : Upper(FIRST_NM4)
        df_exptrans4upper1 = df_rtrtrans2.withColumn("o_FIRST_NM", upper(col("FIRST_NM")))

        #Expression Transformation  #Original Exp : Upper(LAST_NM4)
        df_exptrans4upper2 = df_exptrans4upper1.withColumn("o_LAST_NM", upper(col("LAST_NM")))

        return df_exptrans4upper2

    #Lookup Transformation
    def get_lookup_df_lkptrans(self, df_lkp_demo_source1:DataFrame, df_exptransout:DataFrame):
        self._logger.log_info('lookup Tranformation df_LKPTRANS')
        df_lkptransWindowSpec = Window.partitionBy("ACCT_ID").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
        df_lkp_demo_source1_match_policy = df_lkp_demo_source1.withColumn("rn", row_number().over(df_lkptransWindowSpec)).where(col("rn") == 1).drop(col("rn"))
        df_lkptrans0 = CditUtil.get_lookup_transformation(df_lkp_demo_source1,df_exptransout,df_lkptransWindowSpec,col("LKPTRANS"),['ACCT_ID']).select(df_lkp_demo_source1_match_policy["CUST_ID"],\
        df_lkp_demo_source1_match_policy["LAST_NM"],df_lkp_demo_source1_match_policy["FIRST_NM"],df_exptransout["ACCT_ID"],\
        df_exptransout["ACCT_TYP"],df_exptransout["o_ACCT_STAT_CD"])

        return df_lkptrans0


    #Lookup Transformation
    def get_lookup_df_lkptrans1(self, df_lkp_demo_source2:DataFrame, df_lkptrans0:DataFrame):
        self._logger.log_info('lookup Tranformation df_LKPTRANS1')
        df_lkptrans1WindowSpec = Window.partitionBy("CUST_ID").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
        df_lkp_demo_source2_match_policy = df_lkp_demo_source2.withColumn("rn", row_number().over(df_lkptrans1WindowSpec)).where(col("rn") == 1).drop(col("rn"))
        df_lkptrans10 = CditUtil.get_lookup_transformation(df_lkp_demo_source2,df_lkptrans0,df_lkptrans1WindowSpec,col("LKPTRANS"),['CUST_ID']).select(df_lkptrans0["CUST_ID"],\
        df_lkptrans0["LAST_NM"],df_lkptrans0["FIRST_NM"],df_lkptrans0["ACCT_ID"],\
        df_lkptrans0["ACCT_TYP"],df_lkp_demo_source2_match_policy["CURR_CRDT_BAL_AMT"],df_lkptrans0["o_ACCT_STAT_CD"])

        return df_lkptrans10


    #Multi Joiner Transformation
    def get_multiJoiner_df_jnrtrans(self, df_exptrans1, df_exptrans2out):
        self._logger.log_info('MultiJoiner Tranformation df_jnrtrans')
        df_jnrtrans = df_exptrans1.join(df_exptrans2out, (df_exptrans2out.ACCT_ID == df_exptrans1.ACCT_ID) , how = "inner")\
        .select(df_exptrans1["CUST_ID"],  df_exptrans1["LAST_NM"],  df_exptrans1["FIRST_NM"], \
                 df_exptrans1["ACCT_ID"],  df_exptrans1["ACCT_TYP"], \
                 df_exptrans1["CURR_CRDT_BAL_AMT"],  df_exptrans1["o_ACCT_STAT_CD"])
        return df_jnrtrans

    #Sorter Transformation
    def get_sort_df_srttrans(self, df_jnrtrans):
        self._logger.log_info('Sorter Transformation df_srttrans')
        df_srttrans = df_jnrtrans.orderBy(["ACCT_ID"],ascending=[1])
        return df_srttrans

    #Router Transformation
    def get_router_df_rtrtrans0(self, df_srttrans):
        self._logger.log_info('Router Transformation df_rtrtrans0')
        df_rtrtrans0 = df_srttrans.filter((df_srttrans.ACCT_TYP == 'SB'))
        return df_rtrtrans0

    #Router Transformation
    def get_router_df_rtrtrans1(self, df_srttrans):
        self._logger.log_info('Router Transformation df_rtrtrans1')
        df_rtrtrans1 = df_srttrans.filter((df_srttrans.ACCT_TYP == 'CB'))
        return df_rtrtrans1

    #Router Transformation
    def get_router_df_rtrtrans2(self, df_srttrans):
        self._logger.log_info('Router Transformation df_rtrtrans2')
        df_rtrtrans2 = df_srttrans.filter((df_srttrans.ACCT_TYP == 'RB'))
        return df_rtrtrans2

    #Aggregator Transformation
    def get_agg_df_aggtrans0(self, df_rtrtrans0):
        self._logger.log_info('Aggregator Transformation df_aggtrans0')
        df_aggtrans0 = df_rtrtrans0.groupBy("o_ACCT_STAT_CD").agg(sum('CURR_CRDT_BAL_AMT').alias('sum'))
        return df_aggtrans0