'''
* m_smoketest_infa_very_complex_1.py
* @workflow : wf_m_smoketest_infa_very_complex_1
* @mapping : m_smoketest_infa_very_complex_1
* @date    :Sep 4, 2023
* @Version :CDIT_2.0.11.0
* This code is generated by Cognizant� Data and Intelligence Toolkit (CDIT).
'''

import pyspark
from pyspark.sql import SparkSession,Row
from pyspark.sql import DataFrame
from pyspark.sql import Window
from pyspark.sql.functions import *
from pyspark.sql.types import *
from functools import reduce
from typing import Iterable
from itertools import chain
import datetime
import pandas as pd
import json
from delta.tables import *
from cdit.cditutils import CditUtil
from cdit.m_smoketest_infa_very_complex_1_utils import *
import traceback

def m_smoketest_infa_very_complex_1_main(spark , prg_config , wf_config , mapping_vars , logger , my_reader , my_writer , tr_obj=None, scd_obj=None):

    try:
        tr_obj = MSmoketestInfaVeryComplex1(spark, logger, mapping_vars, prg_config, wf_config)
        query = tr_obj.df_lkp_demo_source1_query()

        #Variables for capturing telemetry information
        src_details = {}
        tgt_details = {}

        df_lsrce1, src_details = my_reader.read_database("Oracle", "idwdev", "LSRCE1", query, src_details)
        df_lsrce1 = df_lsrce1.withColumn("MONOTONICAL_LOOKUP_ORDER", monotonically_increasing_id())

        #Reading Data From Source
        df_msrce1, src_details = my_reader.read_database("Oracle", "idwdev", "MSRCE1", "query", src_details)

        #Lookup Transformation
        df_lkptrans_msrc = tr_obj.get_lookup_df_lkptrans_msrc(df_lsrce1, df_msrce1)
        df_lkptrans_msrc0 = df_lkptrans_msrc

        #Expression Transformation
        df_exptrans_msrc = tr_obj.get_df_exptrans_msrc1(df_lkptrans_msrc0)

        #Expression Transformation MultiOutputs
        logger.log_info('Expression Tranformation MultiOutputs df_exptrans_msrcout')
        df_exptrans_msrcout = df_exptrans_msrc.select('CUSTOMER_ID', 'CUSTOMER_NAME', \
                'CUST_CNTRYCODE', 'O_CNTRYNAME')

        #Filter Transformation
        df_filtrans_msrc = tr_obj.get_filter_df_filtrans_msrc(df_exptrans_msrcout)

        #Column name change
        logger.log_info('Column name change df_filtrans_msrc')
        df_filtrans_msrc_dict = {"o_CNTRYNAME" : "CUST_CNTRYNAME"}

        df_filtrans_msrc_in = CditUtil.column_rename(df_filtrans_msrc, df_filtrans_msrc_dict)

        #Selecting columns that are propagated to next stage
        logger.log_info('Selecting columns that are propagated to next stage df_filtrans_msrc')
        df_filtrans_msrc_out = df_filtrans_msrc_in.select("CUSTOMER_ID", "CUSTOMER_NAME", \
                "CUST_CNTRYNAME", "CUST_CNTRYCODE")

        #Writing data to Target-insert
        tgt_details = my_writer.write_database("Oracle", "idwdev", "TSRCE1", df_filtrans_msrc_out, tgt_details, False)

        #Reading Data From Source
        df_demo_source4, src_details = my_reader.read_database("Oracle", "idwdev", "DEMO_SOURCE4", "query", src_details)

        #Reading Data From Source
        query = tr_obj.df_lkp_demo_source1_query()
        df_lkp_demo_source1, src_details = my_reader.read_database("Oracle", "idwdev", "LKP_DEMO_SOURCE1", query, src_details)
        df_lkp_demo_source1 = df_lkp_demo_source1.withColumn("MONOTONICAL_LOOKUP_ORDER", monotonically_increasing_id())

        #Expression Transformation
        df_exptrans5 = tr_obj.get_df_exptrans51(df_demo_source4)

        #Expression Transformation MultiOutputs
        logger.log_info('Expression Tranformation MultiOutputs df_exptrans5out')
        df_exptrans5out = df_exptrans5.select('ACCT_ID', 'ACCT_TYP', 'O_ACCT_STAT_CD')

        #Reading Data From Source
        query = tr_obj.df_lkp_demo_source2_query()
        df_lkp_demo_source2, src_details = my_reader.read_database("Oracle", "idwdev", "LKP_DEMO_SOURCE2", query, src_details)
        df_lkp_demo_source2 = df_lkp_demo_source2.withColumn("MONOTONICAL_LOOKUP_ORDER", monotonically_increasing_id())

        #Lookup Transformation
        df_lkptrans2_demo = tr_obj.get_lookup_df_lkptrans2_demo(df_lkp_demo_source1, df_exptrans5out)
        df_lkptrans2_demo0 = df_lkptrans2_demo

        #Lookup Transformation
        df_lkptrans11_demo = tr_obj.get_lookup_df_lkptrans11_demo(df_lkp_demo_source2, df_lkptrans2_demo0)
        df_lkptrans11_demo0 = df_lkptrans11_demo

        #Reading Data From Source
        df_lkp_demo_source3, src_details = my_reader.read_database("Oracle", "idwdev", "LKP_DEMO_SOURCE3", "query", src_details)

        #Expression Transformation
        logger.log_info('Expression Tranformation df_exptrans11_demo')
        df_exptrans11_demo = df_lkptrans11_demo0

        #Expression Transformation
        df_exptrans21_demo = tr_obj.get_df_exptrans21_demo1(df_lkp_demo_source3)

        #Expression Transformation MultiOutputs
        logger.log_info('Expression Tranformation MultiOutputs df_exptrans21_demoout')
        df_exptrans21_demoout = df_exptrans21_demo.select('ACCT_ID')

        #Multi Joiner Transformation
        df_jnrtrans1 = tr_obj.get_multiJoiner_df_jnrtrans1(df_exptrans11_demo, df_exptrans21_demoout)

        #Sorter Transformation
        df_srttrans = tr_obj.get_sort_df_srttrans(df_jnrtrans1)

        #Calling Persist Function
        df_srttrans = df_srttrans.persist()


        #Router Transformation
        df_rtrtrans10 = tr_obj.get_router_df_rtrtrans10(df_srttrans)

        #Router Transformation
        df_rtrtrans11 = tr_obj.get_router_df_rtrtrans11(df_srttrans)

        #Router Transformation
        df_rtrtrans12 = tr_obj.get_router_df_rtrtrans12(df_srttrans)

        #Aggregator Transformation
        df_aggtrans0 = tr_obj.get_agg_df_aggtrans0(df_rtrtrans10)

        #Column name change
        logger.log_info('Column name change df_aggtrans0')
        df_aggtrans0_dict = {"o_ACCT_STAT_CD" : "ACCT_STAT_CD", \
                "sum" : "TOTAL_CURR_CRDT_BAL_AMT"}

        df_aggtrans0_in = CditUtil.column_rename(df_aggtrans0, df_aggtrans0_dict)

        #Selecting columns that are propagated to next stage
        logger.log_info('Selecting columns that are propagated to next stage df_aggtrans0')
        df_aggtrans0_out = df_aggtrans0_in.select("ACCT_STAT_CD", "TOTAL_CURR_CRDT_BAL_AMT")

        #Writing data to Target-insert
        tgt_details = my_writer.write_database("Oracle", "idwdev", "DEMO_TARGET_SUM", df_aggtrans0_out, tgt_details, False)

        #Expression Transformation
        df_exptrans4 = tr_obj.get_df_exptrans41(df_rtrtrans12)

        #Expression Transformation name change
        logger.log_info('Expression Tranformation name change df_exptrans4out_namechange')
        df_exptrans4_dict = {"o_FIRST_NM" : "FIRST_NM", "o_LAST_NM" : "LAST_NM"}

        df_exptrans4out_namechange = CditUtil.column_rename(df_exptrans4, df_exptrans4_dict)

        #Selecting columns that are propagated to next stage
        logger.log_info('Selecting columns that are propagated to next stage df_exptrans4out_namechange')
        df_exptrans4out_namechange_out = df_exptrans4out_namechange.select("CUST_ID", \
                "FIRST_NM", "LAST_NM", "ACCT_ID", "ACCT_TYP")

        #Writing data to Target-insert
        tgt_details = my_writer.write_database("Oracle", "idwdev", "DEMO_TARGET_REVOLVING", df_exptrans4out_namechange_out, tgt_details, False)

        #Expression Transformation
        df_exptrans3 = tr_obj.get_df_exptrans31(df_rtrtrans11)

        #Expression Transformation name change
        logger.log_info('Expression Tranformation name change df_exptrans3out_namechange')
        df_exptrans3_dict = {"o_FIRST_NM" : "FIRST_NM", "o_LAST_NM" : "LAST_NM"}

        df_exptrans3out_namechange = CditUtil.column_rename(df_exptrans3, df_exptrans3_dict)

        #Selecting columns that are propagated to next stage
        logger.log_info('Selecting columns that are propagated to next stage df_exptrans3out_namechange')
        df_exptrans3out_namechange_out = df_exptrans3out_namechange.select("CUST_ID", \
                "FIRST_NM", "LAST_NM", "ACCT_ID", "ACCT_TYP")

        #Writing data to Target-insert
        tgt_details = my_writer.write_database("Oracle", "idwdev", "DEMO_TARGET_CURRENT", df_exptrans3out_namechange_out, tgt_details, False)

        #Reading Data From Source
        df_stg_acct, src_details = my_reader.read_database("Oracle", "idwdev", "STG_ACCT", "query", src_details)

        #Reading Data From Source
        df_stg_tx, src_details = my_reader.read_database("Oracle", "idwdev", "STG_TX", "query", src_details)

        #Multi Joiner Transformation
        df_jnrtrans_stg = tr_obj.get_multiJoiner_df_jnrtrans_stg(df_stg_acct, df_stg_tx)

        #Expression Transformation
        df_exptrans_stg = tr_obj.get_df_exptrans_stg1(df_jnrtrans_stg)

        #Expression Transformation MultiOutputs
        logger.log_info('Expression Tranformation MultiOutputs df_exptrans_stgout')
        df_exptrans_stgout = df_exptrans_stg.select('ACCT_ID', 'CRDT_LN', 'CR8_DT', \
                'CLSR_DT', 'ACCT_STAT_CD', 'TX_ID', 'TX_DTTM', 'TX_AMT', 'CUST_ID', \
                'O_ACCT_TYP', 'O_ACCT_DESC', 'O_TX_TYPE_CD')

        #Filter Transformation
        df_filtrans_stg = tr_obj.get_filter_df_filtrans_stg(df_exptrans_stgout)

        #Expression Transformation
        logger.log_info('Expression Tranformation df_exptrans1_stg')
        df_exptrans1_stg = df_filtrans_stg.select("ACCT_ID", "CRDT_LN", "CR8_DT", "CLSR_DT", "ACCT_STAT_CD", "TX_ID", "TX_DTTM",  \
                "TX_AMT", "CUST_ID", "o_ACCT_TYP", "o_ACCT_DESC", "o_TX_TYPE_CD")
        df_filtrans_stg_dict = {"o_ACCT_TYP" : "ACCT_TYP", "o_ACCT_DESC" : "ACCT_DESC",  \
                "CUST_ID" : "ACCT_KEY", "o_TX_TYPE_CD" : "TX_TYPE_CD"}

        df_exptrans1_stg = CditUtil.column_rename(df_exptrans1_stg, df_filtrans_stg_dict)

        #Selecting columns that are propagated to next stage
        logger.log_info('Selecting columns that are propagated to next stage df_exptrans1_stg')
        df_exptrans1_stg_out = df_exptrans1_stg.select("ACCT_ID", "ACCT_TYP", \
                "ACCT_DESC", "CR8_DT", "CRDT_LN", "CLSR_DT", "ACCT_STAT_CD", \
                "TX_ID", "ACCT_KEY", "TX_DTTM", "TX_AMT", "TX_TYPE_CD")

        #Writing data to Target-insert
        tgt_details = my_writer.write_database("Oracle", "idwdev", "CUST_DTL_SUMRY", df_exptrans1_stg_out, tgt_details, False)

        #Unpersist the dataframe
        df_srttrans = df_srttrans.unpersist()


    except Exception as e:
        logger.log_exception(e, src_details, tgt_details)
    finally:
        logger.log_telemetry(src_details, tgt_details)