'''
* m_edw_Rejsekort_StopPoint.py
*
* @date    Jul 28, 2023
*
* @author  CDIT [idwBuddy@cognizant.com]
*
* @par Remarks
*
* This code is generated by Cognizant® Data and Intelligence Toolkit (CDIT).
* Please review the business rules before productionize.
'''
import pyspark
from pyspark.sql import SparkSession,Row
import datetime
import pandas as pd
from pyspark.sql.functions import *
from pyspark.sql import DataFrame
from delta.tables import *
from functools import reduce
from pyspark.sql.types import *
from pyspark.sql import Window
from typing import Iterable
from itertools import chain
import json

#Error Logging
#importing module
import logging
#Creating an object
logger = logging.getLogger()
try:

	#Spark Session initialization
	spark = SparkSession.builder.enableHiveSupport().getOrCreate()

	#Connection_Properties read from json
	config = {}
	with open('/dbfs/mnt/ishare/connection.json', "r") as f:
		config = json.load(f)

	conn_DSA_DataBase = config.get("conn_DSA_DataBase")
	conn_DSA_URL = config.get("conn_DSA_URL")
	conn_DSA_User = config.get("conn_DSA_User")
	conn_DSA_Password = config.get("conn_DSA_Password")
	conn_DSA_Driver = config.get("conn_DSA_Driver")

	conn_EDW_DataBase = config.get("conn_EDW_DataBase")
	conn_EDW_URL = config.get("conn_EDW_URL")
	conn_EDW_User = config.get("conn_EDW_User")
	conn_EDW_Password = config.get("conn_EDW_Password")
	conn_EDW_Driver = config.get("conn_EDW_Driver")

	#configure logger
	logger_filename = config.get("logger_filename")
	logging.basicConfig(filename=logger_filename,
				       format='%(asctime)s %(levelname)s %(message)s',
				       filemode='w')
	#Setting the threshold of logger to DEBUG
    conn_setLevel = config.get("conn_setLevel")
    logger.setLevel(conn_setLevel)
    logger.info('Importing Packages')
	mapVariable_Runs_Remaining_Del = config.get("mapVariable_Runs_Remaining_Del")

	#Reading Data From Source
	query =" SELECT distinct  dr.GeografiskZone,   dr.SiteId,   dr.SiteNr,   dr.StopPointId,   dr.StopPointNr   FROM dsa_REJSEKORT_DELREJSER_DD as dr with (nolock)   INNER JOIN (  select MIN(AarMaaned) as AarMaaned from dsa_Rejsekort_Load with (nolock)  where State_Delrejser_EDW = 'I') as pe  ON pe.AarMaaned = dr.TripYearMonth   "
	override_join_delrejser = read_db_query(spark, conn_DSA_URL, conn_DSA_Driver, query, conn_DSA_User, conn_DSA_Password)

	#Reading Data From Source
	query =" SELECT edw_Rejsekort_StopPoint.SKEY, edw_Rejsekort_StopPoint.StopPointNr, edw_Rejsekort_StopPoint.StopPointId, edw_Rejsekort_StopPoint.SiteNr, edw_Rejsekort_StopPoint.SiteId, edw_Rejsekort_StopPoint.Zone, edw_Rejsekort_StopPoint.CTRL_SYS_INSERT, edw_Rejsekort_StopPoint.CTRL_SRC_SYSTEM FROM edw_Rejsekort_StopPoint ORDER BY StopPointNr, StopPointId, SiteNr, SiteId, Zone "
	edw_rejsekort_stoppoint_s4 = read_db_query(spark, conn_EDW_URL, conn_EDW_Driver, query, conn_EDW_User, conn_EDW_Password).withColumn("MONOTONICAL_LOOKUP_ORDER",monotonically_increasing_id())

	#Lookup Transformation
	lkp_edw_rejsekort_stoppointWindowSpec = Window.partitionBy("Zone","StopPointNr","StopPointId","SiteNr","SiteId").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
	edw_rejsekort_stoppoint_s4_match_policy = edw_rejsekort_stoppoint_s4.withColumn("rn", row_number().over(lkp_edw_rejsekort_stoppointWindowSpec)).where(col("rn") == 1).drop(col("rn"))
	lkp_edw_rejsekort_stoppoint0 = get_lookup_transformation(edw_rejsekort_stoppoint_s4,override_join_delrejser,lkp_edw_rejsekort_stoppointWindowSpec,(override_join_delrejser["GeografiskZone"] == edw_rejsekort_stoppoint_s4_match_policy["Zone"]) & (override_join_delrejser["StopPointNr"] == edw_rejsekort_stoppoint_s4_match_policy["StopPointNr"]) & (override_join_delrejser["StopPointId"] == edw_rejsekort_stoppoint_s4_match_policy["StopPointId"]) & (override_join_delrejser["SiteNr"] == edw_rejsekort_stoppoint_s4_match_policy["SiteNr"]) & (override_join_delrejser["SiteId"] == edw_rejsekort_stoppoint_s4_match_policy["SiteId"]) ,[]).select(override_join_delrejser["SiteId"],\
	override_join_delrejser["SiteNr"],override_join_delrejser["StopPointId"],override_join_delrejser["StopPointNr"],\
	override_join_delrejser["GeografiskZone"],edw_rejsekort_stoppoint_s4_match_policy["SKEY"])

	logger.info('lookup Tranformation LKP_edw_Rejsekort_StopPoint')
	#Filter Transformation
	fil_stoppoint = lkp_edw_rejsekort_stoppoint0.filter(((col("SKEY")).isNull()))
	logger.info('Filter Transformation fil_stoppoint')
	#Expression Transformation
	exp_add_ctrl_fields = get_exp_add_ctrl_fields1(fil_stoppoint)
	logger.info('Expression Tranformation exp_add_ctrl_fields')
	#Expression Transformation name change
	exp_add_ctrl_fieldsout_namechange=exp_add_ctrl_fields.withColumn("Zone",exp_add_ctrl_fields["GeografiskZone"])\
	.withColumn("CTRL_SYS_INSERT",exp_add_ctrl_fields["Session_Start"]).withColumn("CTRL_SRC_SYSTEM",exp_add_ctrl_fields["CTRL_SRC_SYS"])\

	logger.info('Expression Tranformation name change exp_add_ctrl_fieldsout_namechange')
	#Selecting columns that are propagated to next stage
	exp_add_ctrl_fieldsout_namechange=exp_add_ctrl_fieldsout_namechange.select(exp_add_ctrl_fieldsout_namechange["STOPPOINTNR"],\
	exp_add_ctrl_fieldsout_namechange["STOPPOINTID"],exp_add_ctrl_fieldsout_namechange["SITENR"],exp_add_ctrl_fieldsout_namechange["SITEID"],\
	exp_add_ctrl_fieldsout_namechange["Zone"],exp_add_ctrl_fieldsout_namechange["CTRL_SYS_INSERT"],exp_add_ctrl_fieldsout_namechange["CTRL_SRC_SYSTEM"])
	logger.info('Selecting columns that are propagated to next stage exp_add_ctrl_fieldsout_namechange')
	#Writing data to Target-insert
	write_to_db_table_insert(exp_add_ctrl_fieldsout_namechange, conn_EDW_URL, conn_EDW_Driver, conn_EDW_DataBase+".edw_Rejsekort_StopPoint", conn_EDW_User, conn_EDW_Password)
except Exception as e:

	logger.error(e)