'''
* m_STD_AND_PROCEDURE_TO_FACILITY.py
* @mapping :m_STD_AND_PROCEDURE_TO_FACILITY
* @date    :Sep 5, 2023
* @Version :CDIT_2.0.11.0
* This code is generated by Cognizant� Data and Intelligence Toolkit (CDIT).
'''

import pyspark
from pyspark.sql import SparkSession,Row
from pyspark.sql import DataFrame
from pyspark.sql import Window
from pyspark.sql.functions import *
from pyspark.sql.types import *
from functools import reduce
from typing import Iterable
from itertools import chain
import datetime
import pandas as pd
import json
from delta.tables import *
from cdit.cditutils import CditUtil
from cdit.m_STD_AND_PROCEDURE_TO_FACILITY_utils import *
import traceback

def m_STD_AND_PROCEDURE_TO_FACILITY_main(spark , prg_config , wf_config , mapping_vars , logger , my_reader , my_writer , tr_obj=None, scd_obj=None):

    try:
        tr_obj = MStdAndProcedureToFacility(spark, logger, mapping_vars, prg_config, wf_config)

        #Variables for capturing telemetry information
        src_details = {}
        tgt_details = {}

        LOAD_INFO_ID = mapping_vars["LOAD_INFO_ID"]
        SRC_CD_ID = mapping_vars["SRC_CD_ID"]
        ETL_LOAD_TIMESTAMP = mapping_vars["ETL_LOAD_TIMESTAMP"]
        TENANT_ID = mapping_vars["TENANT_ID"]
        RLTNP_TYPE_CD_ID = mapping_vars["RLTNP_TYPE_CD_ID"]

        #Reading Data From Source
        query = tr_obj.df_fclt_query()
    df_fclt, src_details = my_reader.read_database("Netezza", "source_Catalog", "FCLT", query, src_details)
        df_fclt = df_fclt.withColumn("MONOTONICAL_LOOKUP_ORDER", monotonically_increasing_id())

        #Reading Data From Source
        query = tr_obj.df_std_and_prcd_to_fclt_query()
    df_std_and_prcd_to_fclt, src_details = my_reader.read_database("Netezza", "source_Catalog", "STD_AND_PRCD_TO_FCLT", query, src_details)
        df_std_and_prcd_to_fclt = df_std_and_prcd_to_fclt.withColumn("MONOTONICAL_LOOKUP_ORDER", monotonically_increasing_id())

        #Reading Data From Source
        query = tr_obj.df_tidspmst_vw_query()
    df_tidspmst_vw, src_details = my_reader.read_database("Netezza", "source_Catalog", "SQ_TIDSPMST_VW", query, src_details)

        #Reading Data From Source
        query = tr_obj.df_std_and_prcd_query()
    df_std_and_prcd, src_details = my_reader.read_database("Netezza", "source_Catalog", "STD_AND_PRCD", query, src_details)
        df_std_and_prcd = df_std_and_prcd.withColumn("MONOTONICAL_LOOKUP_ORDER", monotonically_increasing_id())

        #Expression Transformation
        df_exptrans = tr_obj.get_df_exptrans1(df_tidspmst_vw)

        #Expression Transformation MultiOutputs
        logger.log_info('Expression Tranformation MultiOutputs df_exptransout')
        df_exptransout = df_exptrans.select('CDC_TARGET_TS', 'STD_AND_PROCEDURE_BK', \
                'FACILITY_BK')

        #Lookup Transformation
        df_lkp_snp = tr_obj.get_lookup_df_lkp_snp(df_std_and_prcd, df_exptransout)
        df_lkp_snp0 = df_lkp_snp

        #Lookup Transformation
        df_lkp_fac = tr_obj.get_lookup_df_lkp_fac(df_fclt, df_lkp_snp0)
        df_lkp_fac0 = df_lkp_fac

        #Lookup Transformation
        df_lkp_tgt = tr_obj.get_lookup_df_lkp_tgt(df_std_and_prcd_to_fclt, df_lkp_fac0)
        df_lkp_tgt0 = df_lkp_tgt

        #Expression Transformation
        df_exptrans1 = tr_obj.get_df_exptrans11(df_lkp_tgt0)

        #Expression Transformation MultiOutputs
        logger.log_info('Expression Tranformation MultiOutputs df_exptrans1out')
        df_exptrans1out = df_exptrans1.select('STD_AND_PRCD_ID', 'FCLT_ID', 'SRC_CD_ID', \
                'RLTNP_TYPE_CD_ID', 'TENANT_ID', 'EFFE_TO_TS', 'EFFE_FM_TS', 'VLD_FM_TS', \
                'LOAD_INFO_ID')

        #Expression Transformation MultiOutputs
        logger.log_info('Expression Tranformation MultiOutputs df_exptrans1out1')
        df_exptrans1out1 = df_exptrans1.select('CDC_TARGET_TS', 'STD_AND_PRCD_ID')

        #Router Transformation
        df_rtrtrans0 = tr_obj.get_router_df_rtrtrans0(df_exptrans1out)

        #Sequence Transformation
        df_seqtrans = tr_obj.get_seq_df_seqtrans(df_exptrans1out1)

        #Aggregator Transformation
        df_agg_etl_load_stats0 = tr_obj.get_agg_df_agg_etl_load_stats0(df_seqtrans)

        #Expression Transformation
        logger.log_info('Expression Tranformation exp_df_rtrtransinsert')
        exp_df_rtrtransinsert = df_rtrtrans0

        #Union Transformation
        df_union = tr_obj.get_union_df_union(exp_df_rtrtransinsert)

        #Expression Transformation
        df_exp_etl_load_stats = tr_obj.get_df_exp_etl_load_stats1(df_agg_etl_load_stats0)

        #Expression Transformation name change
        logger.log_info('Expression Tranformation name change df_exp_etl_load_statsout_namechange')
        df_exp_etl_load_stats_dict = {"O_LOAD_ID" : "LOAD_ID",  \
                "O_CDC_TARGET_TS" : "ETL_LOAD_TIMESTAMP"}

        df_exp_etl_load_statsout_namechange = CditUtil.column_rename(df_exp_etl_load_stats, df_exp_etl_load_stats_dict)

        #Selecting columns that are propagated to next stage
        logger.log_info('Selecting columns that are propagated to next stage df_exp_etl_load_statsout_namechange')
        df_exp_etl_load_statsout_namechange_out = df_exp_etl_load_statsout_namechange.select("LOAD_ID", \
                "FOLDER_NAME", "USER_NAME", "JOB_NAME", "JOBSTREAM_NAME", \
                "WORKFLOW_NAME", "SESSION_NAME", "MAPPING_NAME", "TARGET_TABLE_NAME", \
                "ETL_LOAD_TIMESTAMP", "START_TS", "END_TS")

        #Writing data to Target-insert
        tgt_details = my_writer.write_database("Netezza", "target_Catalog", "ETL_LOAD_STATS", df_exp_etl_load_statsout_namechange_out, tgt_details, False)

        #Column name change
        logger.log_info('Column name change df_union')
        df_union_dict = {"STD_AND_PROCEDURE_ID_SRC" : "STD_AND_PRCD_ID", \
                "FACILITY_ID_SRC" : "FCLT_ID"}

        df_union_in = CditUtil.column_rename(df_union, df_union_dict)

        #Selecting columns that are propagated to next stage
        logger.log_info('Selecting columns that are propagated to next stage df_union')
        df_union_out = df_union_in.select("STD_AND_PRCD_ID", "RLTNP_TYPE_CD_ID", \
                "VLD_FM_TS", "EFFE_FM_TS", "EFFE_TO_TS", "LOAD_INFO_ID", \
                "TENANT_ID", "SRC_CD_ID", "FCLT_ID")

        #Writing data to Target-insert
        tgt_details = my_writer.write_database("Netezza", "target_Catalog", "STD_AND_PRCD_TO_FCLT", df_union_out, tgt_details, False)


    except Exception as e:
        logger.log_exception(e, src_details, tgt_details)
    finally:
        logger.log_telemetry(src_details, tgt_details)