'''
*@date    Sep 5, 2023
* This m_STD_AND_PROCEDURE_TO_FACILITY_utils.py file is a submodule of m_STD_AND_PROCEDURE_TO_FACILITY.py file.
* This code is generated by Cognizant� Data and Intelligence Toolkit (CDIT).
'''
import pyspark
from pyspark.sql.dataframe import DataFrame
from pyspark.sql import Window,WindowSpec,Column
from pyspark.sql.functions import *
from datetime import datetime
from pyspark.sql.session import SparkSession
from pyspark.sql.types import *
import json
from cdit.cditutils import CditUtil
import logging


class MStdAndProcedureToFacility:

    _spark = None
    _logger = None
    _mapping_vars = {}
    _prg_config = {}
    _wf_config = {}

    def __init__(self, spark, logger, mapping_vars, prg_config, wf_config):

        self._spark = spark
        self._logger = logger
        self._prg_config = prg_config
        self._wf_config = wf_config
        self._mapping_vars = mapping_vars

    def df_fclt_query(self):
        self._logger.log_info('Passing query as a parameter for df_fclt ')

        query =""" SELECT FCLT.FCLT_ID, FCLT.FCLT_BK FROM FCLT ORDER BY FCLT_BK """

        return query

    def df_std_and_prcd_to_fclt_query(self):
        self._logger.log_info('Passing query as a parameter for df_std_and_prcd_to_fclt ')

        query ="""SELECT STD_AND_PRCD_TO_FCLT.FCLT_ID as FCLT_ID, STD_AND_PRCD_TO_FCLT.STD_AND_PRCD_ID as STD_AND_PRCD_ID, ROWID as ROWID FROM STD_AND_PRCD_TO_FCLT JOIN TEST_TABLE  WHERE STD_AND_PRCD_TO_FCLT.FCLT_ID=TEST_TABLE.FCLT_ID AND VLD_TO_TS is null ORDER BY STD_AND_PRCD_ID, FCLT_ID, ROWID """

        return query

    def df_tidspmst_vw_query(self):
        self._logger.log_info('Passing query as a parameter for df_tidspmst_vw ')

        query =""" SELECT TIDSPMST_VW.FACILITY as FACILITY_BK, TIDSPMST_VW.SP_NAME ||'_'|| TIDSPMST_VW.FACILITY ||'_'|| TIDSPMST_VW.SP_REVISION AS STD_AND_PROCEDURE_BK,  TIDSPMST_VW.CDC_TARGET_TS AS CDC_TARGET_TS  FROM TIDSPMST_VW  JOIN TIDFAMST_VW ON TIDSPMST_VW.FACILITY=TIDFAMST_VW.FACILITY  WHERE DATE(TIDSPMST_VW.CDC_TARGET_TS) > DATE(TO_TIMESTAMP('"""+ self._mapping_vars["ETL_LOAD_TIMESTAMP"] +"""','YYYY-MM-DD HH24:MI:SS.US')) """

        return query

    def df_std_and_prcd_query(self):
        self._logger.log_info('Passing query as a parameter for df_std_and_prcd ')

        query =""" SELECT STD_AND_PRCD.STD_AND_PRCD_BK, STD_AND_PRCD.STD_AND_PRCD_ID FROM STD_AND_PRCD ORDER BY STD_AND_PRCD_BK """

        return query


    def get_df_exptrans1(self, df_tidspmst_vw:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans1') 
        #Expression Transformation  #Original Exp : SETMAXVARIABLE($$ETL_LOAD_TIMESTAMP,(TO_CHAR(CDC_TARGET_TS,'YYYY-MM-DD HH24:MI:SS.US')))
        df_exptransgeneral1 = df_tidspmst_vw.withColumn("ETL_LOAD_TIMESTAMP", greatest(lit(self._mapping_vars["ETL_LOAD_TIMESTAMP"]),(to_timestamp(col("CDC_TARGET_TS"),lit("""yyyy-MM-dd HH24:MI:SS.US""")))))
    
        return df_exptransgeneral1


    def get_df_exptrans11(self, df_lkp_tgt0:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans11') 
        #Expression Transformation  #Original Exp : $$SRC_CD_ID
        df_exptrans1general1 = df_lkp_tgt0.withColumn("SRC_CD_ID", lit(self._mapping_vars["SRC_CD_ID"]))
    
        #Expression Transformation  #Original Exp : 'STD_AND_PRCD_TO_FCLT'
        df_exptrans1general2 = df_exptrans1general1.withColumn("TABLE_NAME", lit("STD_AND_PRCD_TO_FCLT"))
    
        #Expression Transformation  #Original Exp : $$RLTNP_TYPE_CD_ID
        df_exptrans1general3 = df_exptrans1general2.withColumn("RLTNP_TYPE_CD_ID", lit(self._mapping_vars["RLTNP_TYPE_CD_ID"]))
    
        #Expression Transformation  #Original Exp : $$TENANT_ID
        df_exptrans1general4 = df_exptrans1general3.withColumn("TENANT_ID", lit(self._mapping_vars["TENANT_ID"]))
    
        #Expression Transformation  #Original Exp : sysdate
        df_exptrans1SYSDATE5 = df_exptrans1general4.withColumn("EFFE_TO_TS", current_timestamp())
    
        #Expression Transformation  #Original Exp : sysdate
        df_exptrans1SYSDATE6 = df_exptrans1SYSDATE5.withColumn("EFFE_FM_TS", current_timestamp())
    
        #Expression Transformation  #Original Exp : systimestamp()
        df_exptrans1SYSDATE7 = df_exptrans1SYSDATE6.withColumn("VLD_FM_TS", current_timestamp())
    
        #Expression Transformation  #Original Exp : $$LOAD_INFO_ID
        df_exptrans1general8 = df_exptrans1SYSDATE7.withColumn("LOAD_INFO_ID", lit(self._mapping_vars["LOAD_INFO_ID"]))
    
        return df_exptrans1general8


    def get_df_exp_etl_load_stats1(self, df_agg_etl_load_stats0:DataFrame):

        self._logger.log_info('Expression Transformation df_exp_etl_load_stats1') 
        #Expression Transformation  #Original Exp : 'JOB_NAME'
        df_exp_etl_load_statsgeneral1 = df_agg_etl_load_stats0.withColumn("JOB_NAME", lit("JOB_NAME"))
    
        #Expression Transformation  #Original Exp : 'STD_AND_PROCEDURE_TO_FACILITY'
        df_exp_etl_load_statsgeneral2 = df_exp_etl_load_statsgeneral1.withColumn("TARGET_TABLE_NAME", lit("STD_AND_PROCEDURE_TO_FACILITY"))
    
        #Expression Transformation  #Original Exp : 'JOBSTREAM_NAME'
        df_exp_etl_load_statsgeneral3 = df_exp_etl_load_statsgeneral2.withColumn("JOBSTREAM_NAME", lit("JOBSTREAM_NAME"))
    
        return df_exp_etl_load_statsgeneral3

    #Lookup Transformation
    def get_lookup_df_lkp_snp(self, df_std_and_prcd:DataFrame, df_exptransout:DataFrame):
        self._logger.log_info('lookup Tranformation df_LKP_SnP')
        df_lkp_snpWindowSpec = Window.partitionBy("STD_AND_PRCD_BK").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
        df_std_and_prcd_match_policy = df_std_and_prcd.withColumn("rn", row_number().over(df_lkp_snpWindowSpec)).where(col("rn") == 1).drop(col("rn"))
        df_lkp_snp0 = CditUtil.get_lookup_transformation(df_std_and_prcd,df_exptransout,df_lkp_snpWindowSpec,(df_exptransout["STD_AND_PROCEDURE_BK"] == df_std_and_prcd_match_policy["STD_AND_PRCD_BK"]) ,[]).select(df_exptransout["CDC_TARGET_TS"],\
        df_exptransout["FACILITY_BK"],df_std_and_prcd_match_policy["STD_AND_PRCD_ID"])

        return df_lkp_snp0
    

    #Lookup Transformation
    def get_lookup_df_lkp_fac(self, df_fclt:DataFrame, df_lkp_snp0:DataFrame):
        self._logger.log_info('lookup Tranformation df_LKP_FAC')
        df_lkp_facWindowSpec = Window.partitionBy("FCLT_BK").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
        df_fclt_match_policy = df_fclt.withColumn("rn", row_number().over(df_lkp_facWindowSpec)).where(col("rn") == 1).drop(col("rn"))
        df_lkp_fac0 = CditUtil.get_lookup_transformation(df_fclt,df_lkp_snp0,df_lkp_facWindowSpec,(df_lkp_snp0["FACILITY_BK"] == df_fclt_match_policy["FCLT_BK"]) ,[]).select(df_lkp_snp0["CDC_TARGET_TS"],\
        df_lkp_snp0["STD_AND_PRCD_ID"],df_fclt_match_policy["FCLT_ID"])

        return df_lkp_fac0
    

    #Lookup Transformation
    def get_lookup_df_lkp_tgt(self, df_std_and_prcd_to_fclt:DataFrame, df_lkp_fac0:DataFrame):
        self._logger.log_info('lookup Tranformation df_LKP_TGT')
        df_lkp_tgtWindowSpec = Window.partitionBy("STD_AND_PRCD_ID").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
        df_std_and_prcd_to_fclt_match_policy = df_std_and_prcd_to_fclt.withColumn("rn", row_number().over(df_lkp_tgtWindowSpec)).where(col("rn") == 1).drop(col("rn"))
        df_lkp_tgt0 = CditUtil.get_lookup_transformation(df_std_and_prcd_to_fclt,df_lkp_fac0,df_lkp_tgtWindowSpec,col("LKPTRANS"),['STD_AND_PRCD_ID']).select(df_lkp_fac0["CDC_TARGET_TS"],\
        df_lkp_fac0["STD_AND_PRCD_ID"],df_lkp_fac0["FCLT_ID"])

        return df_lkp_tgt0
    

    #Router Transformation
    def get_router_df_rtrtrans0(self, df_exptrans1out):
        self._logger.log_info('Router Transformation df_rtrtrans0')
        df_rtrtrans0 = df_exptrans1out.filter((((df_exptrans1out.STD_AND_PRCD_ID).isNull())))
        return df_rtrtrans0

    #Sequence Transformation
    def get_seq_df_seqtrans(df_exptrans1out1:DataFrame):
        self._logger.log_info('sequence Transformation df_seqtrans')
        
        df_seqtrans=df_exptrans1out1.withColumn("tempid", monotonically_increasing_id()).withColumn('row_num', row_number().over(Window.orderBy(col('tempid')))).withColumn("ID",((col("row_num")-lit(1))*lit(1)))
        return df_seqtrans

    #Aggregator Transformation
    def get_agg_df_agg_etl_load_stats0(self, df_seqtrans):
        self._logger.log_info('Aggregator Transformation df_agg_etl_load_stats0')
        df_agg_etl_load_stats0 = df_seqtrans.withColumn("MAPPING_NAME",$PMMappingName)
df_agg_etl_load_stats0 = df_agg_etl_load_stats0.agg(when(((col("ID")).isNull()),to_date('19000101','yyyyMMdd')).otherwise(col("CDC_TARGET_TS")).alias("V_CDC_TARGET_TS"),max('V_CDC_TARGET_TS').alias('O_CDC_TARGET_TS'),max('SYSDATE').alias('END_TS'),min('SESSSTARTTIME').alias('START_TS'),max('STD_AND_PRCD_ID').alias('O_LOAD_ID'),last('ID').alias('ID'))
        return df_agg_etl_load_stats0

    #Union Transformation
    def get_union_df_union(self, exp_df_rtrtransinsert):
        self._logger.log_info('Union Transformation df_union')
        df_union = exp_df_rtrtransinsert \
        .select(exp_df_rtrtransinsert["EFFE_FM_TS"].cast("timestamp"), \
                exp_df_rtrtransinsert["LOAD_INFO_ID"].cast("long"), \
                exp_df_rtrtransinsert["VLD_FM_TS"].cast("timestamp"), \
                exp_df_rtrtransinsert["STD_AND_PRCD_ID"].alias("STD_AND_PROCEDURE_ID_SRC").cast("long"), \
                exp_df_rtrtransinsert["FCLT_ID"].alias("FACILITY_ID_SRC").cast("long"), \
                exp_df_rtrtransinsert["TENANT_ID"].cast("long"), \
                exp_df_rtrtransinsert["RLTNP_TYPE_CD_ID"].cast("long"), \
                exp_df_rtrtransinsert["SRC_CD_ID"].cast("long"), \
                exp_df_rtrtransinsert["EFFE_TO_TS"].cast("timestamp"))
        return df_union