'''
*@date    Sep 4, 2023
* This m_smoketest_infa_very_complex_1_utils.py file is a submodule of m_smoketest_infa_very_complex_1.py file.
* This code is generated by Cognizant� Data and Intelligence Toolkit (CDIT).
'''
import pyspark
from pyspark.sql.dataframe import DataFrame
from pyspark.sql import Window,WindowSpec,Column
from pyspark.sql.functions import *
from datetime import datetime
from pyspark.sql.session import SparkSession
from pyspark.sql.types import *
import json
from cdit.cditutils import CditUtil
import logging


class MSmoketestInfaVeryComplex1:

    _spark = None
    _logger = None
    _mapping_vars = {}
    _prg_config = {}
    _wf_config = {}

    def __init__(self, spark, logger, mapping_vars, prg_config, wf_config):

        self._spark = spark
        self._logger = logger
        self._prg_config = prg_config
        self._wf_config = wf_config
        self._mapping_vars = mapping_vars

    def df_lsrce1_query(self):
        self._logger.log_info('Passing query as a parameter for df_lsrce1 ')

        query =""" SELECT LSRCE1.CUST_CNTRYCODE, LSRCE1.CUST_CNTRYNAME FROM LSRCE1 ORDER BY CUST_CNTRYNAME """

        return query


    def get_df_exptrans_msrc1(self, df_lkptrans_msrc0:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans_msrc1') 
        #Expression Transformation  #Original Exp : UPPER(CNTRYNAME)
        df_exptrans_msrcupper1 = df_lkptrans_msrc0.withColumn("o_CNTRYNAME", upper(col("CNTRYNAME")))
    
        return df_exptrans_msrcupper1

    def df_lkp_demo_source1_query(self):
        self._logger.log_info('Passing query as a parameter for df_lkp_demo_source1 ')

        query =""" SELECT LKP_DEMO_SOURCE1.CUST_ID, LKP_DEMO_SOURCE1.ACCT_ID, LKP_DEMO_SOURCE1.FIRST_NM, LKP_DEMO_SOURCE1.LAST_NM, LKP_DEMO_SOURCE1.CUST_ADDR, LKP_DEMO_SOURCE1.CUST_PHN, LKP_DEMO_SOURCE1.CUST_EML_ADDR, LKP_DEMO_SOURCE1.AGE, LKP_DEMO_SOURCE1.DOB, LKP_DEMO_SOURCE1.CUST_TYP FROM LKP_DEMO_SOURCE1 ORDER BY ACCT_ID """

        return query


    def get_df_exptrans51(self, df_demo_source4:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans51') 
        #Expression Transformation  #Original Exp : LTRIM(ACCT_DESC)
        df_exptrans5ltrim1 = df_demo_source4.withColumn("o_ACCT_DESC", ltrim(col("ACCT_DESC")))
    
        #Expression Transformation  #Original Exp : INITCAP(ACCT_STAT_CD)
        df_exptrans5initcap2 = df_exptrans5ltrim1.withColumn("o_ACCT_STAT_CD", initcap(col("ACCT_STAT_CD")))
    
        return df_exptrans5initcap2

    def df_lkp_demo_source2_query(self):
        self._logger.log_info('Passing query as a parameter for df_lkp_demo_source2 ')

        query =""" SELECT LKP_DEMO_SOURCE2.CUST_ID, LKP_DEMO_SOURCE2.CRDT_SCORE, LKP_DEMO_SOURCE2.MAX_CRDT_SCORE, LKP_DEMO_SOURCE2.MIN_CRDT_SCORE, LKP_DEMO_SOURCE2.MAX_CRDT_LMT, LKP_DEMO_SOURCE2.CURR_CRDT_BAL_AMT, LKP_DEMO_SOURCE2.AVG_INC_AMT FROM LKP_DEMO_SOURCE2 ORDER BY CUST_ID """

        return query


    def get_df_exptrans21_demo1(self, df_lkp_demo_source3:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans21_demo1') 
        #Expression Transformation  #Original Exp : INITCAP(TX_TYPE_DESC)
        df_exptrans21_demoinitcap1 = df_lkp_demo_source3.withColumn("o_TX_TYPE_DESC", initcap(col("TX_TYPE_DESC")))
    
        return df_exptrans21_demoinitcap1


    def get_df_exptrans41(self, df_rtrtrans12:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans41') 
        #Expression Transformation  #Original Exp : Upper(FIRST_NM4)
        df_exptrans4upper1 = df_rtrtrans12.withColumn("o_FIRST_NM", upper(col("FIRST_NM")))
    
        #Expression Transformation  #Original Exp : Upper(LAST_NM4)
        df_exptrans4upper2 = df_exptrans4upper1.withColumn("o_LAST_NM", upper(col("LAST_NM")))
    
        return df_exptrans4upper2


    def get_df_exptrans31(self, df_rtrtrans11:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans31') 
        #Expression Transformation  #Original Exp : Upper(FIRST_NM3)
        df_exptrans3upper1 = df_rtrtrans11.withColumn("o_FIRST_NM", upper(col("FIRST_NM")))
    
        #Expression Transformation  #Original Exp : Upper(LAST_NM3)
        df_exptrans3upper2 = df_exptrans3upper1.withColumn("o_LAST_NM", upper(col("LAST_NM")))
    
        return df_exptrans3upper2


    def get_df_exptrans_stg1(self, df_jnrtrans_stg:DataFrame):

        self._logger.log_info('Expression Transformation df_exptrans_stg1') 
        #Expression Transformation  #Original Exp : LTRIM(ACCT_TYP)
        df_exptrans_stgltrim1 = df_jnrtrans_stg.withColumn("o_ACCT_TYP", ltrim(col("ACCT_TYP")))
    
        #Expression Transformation  #Original Exp : lower(ACCT_DESC)
        df_exptrans_stglower2 = df_exptrans_stgltrim1.withColumn("o_ACCT_DESC", lower(col("ACCT_DESC")))
    
        #Expression Transformation  #Original Exp : INITCAP(TX_TYPE_CD)
        df_exptrans_stginitcap3 = df_exptrans_stglower2.withColumn("o_TX_TYPE_CD", initcap(col("TX_TYPE_CD")))
    
        return df_exptrans_stginitcap3

    #Lookup Transformation
    def get_lookup_df_lkptrans_msrc(self, df_lsrce1:DataFrame, df_msrce1:DataFrame):
        self._logger.log_info('lookup Tranformation df_LKPTRANS_MSRC')
        df_lkptrans_msrcWindowSpec = Window.partitionBy("CUST_CNTRYNAME").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
        df_lsrce1_match_policy = df_lsrce1.withColumn("rn", row_number().over(df_lkptrans_msrcWindowSpec)).where(col("rn") == 1).drop(col("rn"))
        df_lkptrans_msrc0 = CditUtil.get_lookup_transformation(df_lsrce1,df_msrce1,df_lkptrans_msrcWindowSpec,(df_msrce1["CNTRYNAME"] == df_lsrce1_match_policy["CUST_CNTRYNAME"]) ,[]).select(df_msrce1["CUSTOMER_ID"],\
        df_msrce1["CUSTOMER_NAME"],df_msrce1["CNTRYNAME"],df_lsrce1_match_policy["CUST_CNTRYCODE"])

        return df_lkptrans_msrc0
    

    #Filter Transformation
    def get_filter_df_filtrans_msrc(self, df_exptrans_msrcout:DataFrame):
        self._logger.log_info('Filter Transformation df_filtrans_msrc')
        df_filtrans_msrc = df_exptrans_msrcout.filter(col("o_CNTRYNAME")=='INDIA')
        return df_filtrans_msrc

    #Lookup Transformation
    def get_lookup_df_lkptrans2_demo(self, df_lkp_demo_source1:DataFrame, df_exptrans5out:DataFrame):
        self._logger.log_info('lookup Tranformation df_LKPTRANS2_DEMO')
        df_lkptrans2_demoWindowSpec = Window.partitionBy("ACCT_ID").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
        df_lkp_demo_source1_match_policy = df_lkp_demo_source1.withColumn("rn", row_number().over(df_lkptrans2_demoWindowSpec)).where(col("rn") == 1).drop(col("rn"))
        df_lkptrans2_demo0 = CditUtil.get_lookup_transformation(df_lkp_demo_source1,df_exptrans5out,df_lkptrans2_demoWindowSpec,col("LKPTRANS"),['ACCT_ID']).select(df_lkp_demo_source1_match_policy["CUST_ID"],\
        df_lkp_demo_source1_match_policy["FIRST_NM"],df_lkp_demo_source1_match_policy["LAST_NM"],df_exptrans5out["ACCT_ID"],\
        df_exptrans5out["ACCT_TYP"],df_exptrans5out["o_ACCT_STAT_CD"])

        return df_lkptrans2_demo0
    

    #Lookup Transformation
    def get_lookup_df_lkptrans11_demo(self, df_lkp_demo_source2:DataFrame, df_lkptrans2_demo0:DataFrame):
        self._logger.log_info('lookup Tranformation df_LKPTRANS11_DEMO')
        df_lkptrans11_demoWindowSpec = Window.partitionBy("CUST_ID").orderBy(col("MONOTONICAL_LOOKUP_ORDER").asc())
        df_lkp_demo_source2_match_policy = df_lkp_demo_source2.withColumn("rn", row_number().over(df_lkptrans11_demoWindowSpec)).where(col("rn") == 1).drop(col("rn"))
        df_lkptrans11_demo0 = CditUtil.get_lookup_transformation(df_lkp_demo_source2,df_lkptrans2_demo0,df_lkptrans11_demoWindowSpec,col("LKPTRANS"),['CUST_ID']).select(df_lkptrans2_demo0["CUST_ID"],\
        df_lkptrans2_demo0["FIRST_NM"],df_lkptrans2_demo0["LAST_NM"],df_lkptrans2_demo0["ACCT_ID"],\
        df_lkptrans2_demo0["ACCT_TYP"],df_lkp_demo_source2_match_policy["CURR_CRDT_BAL_AMT"],df_lkptrans2_demo0["o_ACCT_STAT_CD"])

        return df_lkptrans11_demo0
    

    #Multi Joiner Transformation
    def get_multiJoiner_df_jnrtrans1(self, df_exptrans11_demo, df_exptrans21_demoout):
        self._logger.log_info('MultiJoiner Tranformation df_jnrtrans1')
        df_jnrtrans1 = df_exptrans11_demo.join(df_exptrans21_demoout, (df_exptrans21_demoout.ACCT_ID == df_exptrans11_demo.ACCT_ID) , how = "inner")\
        .select(df_exptrans11_demo["CUST_ID"],  df_exptrans11_demo["FIRST_NM"], \
                 df_exptrans11_demo["LAST_NM"],  df_exptrans11_demo["ACCT_ID"], \
                 df_exptrans11_demo["ACCT_TYP"],  df_exptrans11_demo["CURR_CRDT_BAL_AMT"], \
                 df_exptrans11_demo["o_ACCT_STAT_CD"])
        return df_jnrtrans1

    #Sorter Transformation
    def get_sort_df_srttrans(self, df_jnrtrans1):
        self._logger.log_info('Sorter Transformation df_srttrans')
        df_srttrans = df_jnrtrans1.orderBy(["ACCT_ID"],ascending=[1])
        return df_srttrans

    #Router Transformation
    def get_router_df_rtrtrans10(self, df_srttrans):
        self._logger.log_info('Router Transformation df_rtrtrans10')
        df_rtrtrans10 = df_srttrans.filter((df_srttrans.ACCT_TYP == 'SB'))
        return df_rtrtrans10

    #Router Transformation
    def get_router_df_rtrtrans11(self, df_srttrans):
        self._logger.log_info('Router Transformation df_rtrtrans11')
        df_rtrtrans11 = df_srttrans.filter((df_srttrans.ACCT_TYP == 'CB'))
        return df_rtrtrans11

    #Router Transformation
    def get_router_df_rtrtrans12(self, df_srttrans):
        self._logger.log_info('Router Transformation df_rtrtrans12')
        df_rtrtrans12 = df_srttrans.filter((df_srttrans.ACCT_TYP == 'RB'))
        return df_rtrtrans12

    #Aggregator Transformation
    def get_agg_df_aggtrans0(self, df_rtrtrans10):
        self._logger.log_info('Aggregator Transformation df_aggtrans0')
        df_aggtrans0 = df_rtrtrans10.groupBy("o_ACCT_STAT_CD").agg(sum('CURR_CRDT_BAL_AMT').alias('sum'))
        return df_aggtrans0

    #Multi Joiner Transformation
    def get_multiJoiner_df_jnrtrans_stg(self, df_stg_acct, df_stg_tx):
        self._logger.log_info('MultiJoiner Tranformation df_jnrtrans_stg')
        df_jnrtrans_stg = df_stg_acct.join(df_stg_tx, (df_stg_tx.ACCT_ID == df_stg_acct.ACCT_ID) , how = "inner")\
        .select(df_stg_acct["ACCT_ID"],  df_stg_acct["CRDT_LN"],  df_stg_acct["CR8_DT"], \
                 df_stg_acct["CLSR_DT"],  df_stg_acct["ACCT_STAT_CD"], \
                 df_stg_acct["ACCT_TYP"],  df_stg_acct["ACCT_DESC"],  df_stg_tx["TX_ID"], \
                 df_stg_tx["TX_DTTM"],  df_stg_tx["TX_AMT"],  df_stg_tx["CUST_ID"], \
                 df_stg_tx["TX_TYPE_CD"])
        return df_jnrtrans_stg

    #Filter Transformation
    def get_filter_df_filtrans_stg(self, df_exptrans_stgout:DataFrame):
        self._logger.log_info('Filter Transformation df_filtrans_stg')
        df_filtrans_stg = df_exptrans_stgout.filter(((col("o_ACCT_TYP")=='SB')) | ((col("o_ACCT_TYP")=='CB')))
        return df_filtrans_stg