server.port=7002
spring.application.name=User

#consumer configuration
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.String
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.String

spring.kafka.consumer.group-id=g1
spring.kafka.consumer.auto-offset-reset=earliest