server.port=7002
spring.application.name=UserContactDetails

logging.file.name=C:/Nitesh/LogLocation/${spring.application.name}.log
logging.level.root=info

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.client.instance.preferIpAddress=true